# Generated by Django 2.1.7 on 2019-03-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(blank=True, max_length=100)),
                ('mobileno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionX', models.IntegerField()),
                ('PositionY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roboId', models.CharField(max_length=100)),
                ('roboStatus', models.CharField(max_length=100)),
                ('roboPhase', models.CharField(max_length=100)),
                ('roboPositionX', models.IntegerField()),
                ('roboPositionY', models.IntegerField()),
                ('taskId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('userFingerprintId', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(blank=True, max_length=100)),
                ('mobileno', models.IntegerField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='mainapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfTrans', models.TimeField(default=None)),
                ('message', models.CharField(max_length=1000)),
                ('receiverId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rid', to='mainapp.RoboUser')),
                ('robo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robotid', to='mainapp.Robot')),
                ('senderId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sid', to='mainapp.RoboUser')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ManyToManyField(related_name='user', to='mainapp.RoboUser'),
        ),
    ]
